project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "EDS 221"
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: https://docs.google.com/document/d/13wWvGrbbH0INB4JHi27EE845Nq3Tlh4SOIfebd2u3Ng/view?usp=sharing
        target: _blank
      - text: daily materials
        menu: 
          - text: day 1 (8/12)
            href: course-materials/day1.qmd
          - text: day 2 (8/13)
            href: course-materials/day2.qmd
          - text: day 3 (8/14)
            href: course-materials/day3.qmd
          - text: day 4 (8/15)
            href: course-materials/day4.qmd
          - text: day 5 (8/16)
            href: course-materials/day5.qmd
          - text: day 6 (8/19)
            href: course-materials/day6.qmd
          - text: day 7 (8/20)
            href: course-materials/day7.qmd
          - text: day 8 (8/21)
            href: course-materials/day8.qmd
          - text: day 9 (8/22)
            href: course-materials/day9.qmd
          - text: day 10 (8/23)
            href: course-materials/day10.qmd
      - icon: github
        href: https://github.com/EDS-221
        target: _blank
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/samanthacsik/EDS-212-essential-math), [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html) and [Quarto](https://quarto.org/)
    left: |
      <img src="images/bren-logo.png" alt="The Bren School of Environmental Science & Management logo" width="250"/>


format:
  html:
    theme: meds-website-styles.scss
    toc: true
    title-block-banner: true
    page-layout: full

editor: source



