---
title: "Interactive Session 1B"
subtitle: "File paths, `here`, project structure, code style"
editor_options: 
  chunk_output_type: console
---

## 1. Setup

- Fork and clone [this repo](https://github.com/eds-221-programming-essentials/eds221-day1-comp)
- Check out the project structure & files

## 2. File path practice

- We'll run through each line in the `toolik_airtemp_summary.qmd` to understand where it's pointing, what it's doing, and add a few more tools to our coding toolkit (`readr::read_csv()`, `janitor::clean_names()`, `%>%`)

- Similarly, we'll create from scratch & work through one more example. We will: 

  - Read in the chlorophyll data
  - Explore the imported data
  - Clean up the dataset names
  - Create a plot of chlorophyll concentration at varying measurement depth, do some customization
  - Export the graph to /figs
  
::: {.callout-tip collapse=true}
## Solution
```{r}
#| eval: false
#| echo: true

# read in data
toolik_chlorophyll <- read_csv(here::here("data", "data-raw", "toolik_chlorophyll.csv"))

# get data overview
skimr::skim(toolik_chlorophyll)

dim(toolik_chlorophyll)
names(toolik_chlorophyll)

# clean names
toolik_chlorophyll <- toolik_chlorophyll %>% clean_names() 

# make plot
toolik_chlorophyll_plot <- ggplot(data = toolik_chlorophyll, 
                                  aes(x = depth, y = as.numeric(active_chl_a_ug_l))) +
  geom_point() +
  theme_minimal() +
  labs(title = "Toolik Station Chlorophyll a concentration",
       x = "Depth (m)",
       y = "Chlorophyll a concentration (micrograms per liter)")

toolik_chlorophyll_plot

# save plot
ggsave(here::here("figs", "toolik_chlorophyll_plot.png"), height = 6, width = 7)
```
:::  


## 3. Data sources 

All datasets are collected and provided by scientists with the [Toolik Station Long Term Ecological Research](https://www.uaf.edu/toolik/) (LTER) site, Alaska.

**Toolik Station Meteorological Data: toolik_weather.csv** Shaver, G. 2019. A multi-year DAILY weather file for the Toolik Field Station at Toolik Lake, AK starting 1988 to present. ver 4. Environmental Data Initiative. https://doi.org/10.6073/pasta/ce0f300cdf87ec002909012abefd9c5c (Accessed 2021-08-08).

**Toolik Lake Chlorophyll: toolik_chlorophyll.csv**  Miller, M. 2014. Chlorophyll A, and primary productivity of Toolik lake , Arctic LTER 1975 to 1988, Toolik Filed Station, Alaska. ver 5. Environmental Data Initiative. https://doi.org/10.6073/pasta/6738024bf0174f73b3f74486f43d1059 (Accessed 2021-08-08).

**Toolik fish: toolik_fish.csv** Budy, P., C. Luecke, and M. McDonald. 2020. Fish captures in lakes of the Arctic LTER region Toolik Field Station Alaska from 1986 to present. ver 6. Environmental Data Initiative. https://doi.org/10.6073/pasta/d0a9358f783339821b82510eb8c61b45 (Accessed 2021-08-08).

::: {.center-text .body-text-xl .teal-text}
End Interactive Session 2A
:::
