---
title: "Day 9 Tasks & Activities"
subtitle: "Troubleshooting, `{reprex}`, and working with data continued"
---

## 1. Setup

- Fork [this repo](https://github.com/eds-221-programming-essentials/eds221-day9-activities)
- In your fork, under 'Settings', check the box next to Issues (this is so you'll be able to submit issues to yourself containing reprex)
- Clone to create a version-controlled R Project
- Explore the contents a bit to familiarize yourself with the structure

## Task 1: SOS - Save this script

- Open the `busted_birds.Rmd` file
- Try to knit it (R Markdown's version of rendering). Not happening.
- **Make a copy** of the file (in the project root) called `fixed_birds.Rmd`
- Work through the code from the top line down, fixing errors where indicated and using the hints for what the code is actually trying to do. 

::: {.callout-note}
## Note 
It's not enough to just get the code to run. You need to actually make sure it's doing what you expect it to do by checking and understanding the outputs of *each line*. 
:::

## Task 2: Help a friend by making some `reprex`

- Open the `reprex_practice.Rmd` file
- There are two separate code chunks in the .Rmd, neither run.
- First, try to figure out what the code in each chunk is trying to do.
- Then, determine where the code breaks (there is only one breaking point for each chunk)
- Then, for each **create a reprex** that provides a minimal out-of-the-box reproducible *working* example of the thing in the code that isn't working. Create your reprex in a separate code chunk below each broken example. Use `{reprex}` to render your reproducible example for sharing on GitHub. Add your reprexes as issues to one of your neighbor's GitHub repo for the day 9 activities to help them out! (you'll need to ask what they're username is so you can find their repo on GitHub at `username/eds221-day9-activities`) 

::: {.center-text .body-text-xl .teal-text}
End Activity Session (Day 8)
:::